# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  aws-ecr: circleci/aws-ecr@6.15.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.12
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}-{{ checksum "Makefile" }}
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: sudo apt-get update
      - run:
          name: Build Fluent-Bit image
          command: |
            docker version
            docker images
            make release
            docker images
            docker tag amazon/aws-for-fluent-bit:latest $AWS_ECR_DOMAIN/$AWS_ECR_NAME:$CIRCLE_SHA1
            docker images
      - save_cache:
          key: build-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}-{{ checksum "Makefile" }}
          paths:
            - ~/.
      - aws-ecr/ecr-login:
          account-url: AWS_ECR_DOMAIN
      - aws-ecr/push-image:
          account-url: AWS_ECR_DOMAIN
          repo: aws-for-fluent-bit-test
          tag: $CIRCLE_SHA1
      - save_cache:
          key: build-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}-{{ checksum "Makefile" }}
          paths:
            - ~/.

workflows:
  build_image:
    jobs:
      - build:
          context: nvirginia-test

