# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  aws-ecr: circleci/aws-ecr@6.15.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: sudo apt-get update
      - aws-ecr/ecr-login:
          account-url: AWS_ECR_DOMAIN
      - run:
          name: Build Fluent-Bit image
          command: |
            make release
            docker tag amazon/aws-for-fluent-bit:latest ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/aws-for-fluent-bit:$CIRCLE_BUILD_NUM
            docker tag amazon/aws-for-fluent-bit:latest ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/aws-for-fluent-bit:latest
            docker images
      - aws-ecr/push-image:
          account-url: AWS_ECR_DOMAIN
          repo: 'aws-for-fluent-bit'
          tag: $CIRCLE_BUILD_NUM,latest

workflows:
  build_image:
    jobs:
      - build:
          context: nvirginia-test

#            make release
#            aws ecr get-login-password --region $AWS_REGION --profile default | docker login --username AWS --password-stdin $AWS_ECR_DOMAIN
#            docker tag amazon/aws-for-fluent-bit:latest 991828066748.dkr.ecr.us-east-1.amazonaws.com/aws-for-fluent-bit:$CIRCLE_BUILD_NUM
#            docker push 991828066748.dkr.ecr.us-east-1.amazonaws.com/aws-for-fluent-bit:$CIRCLE_BUILD_NUM
#      - aws-ecr/push-image:
#          account-url: AWS_ECR_DOMAIN
#          repo: '${AWS_ECR_NAME}'
#          tag: '${$CIRCLE_BUILD_NUM}'
#      - run:
#          name: Push to ECR
#          command: |
#            docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/aws-for-fluent-bit:$CIRCLE_BUILD_NUM
